apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: ipl-replicaset
  namespace: murali-ns
spec: 
  replicas: 5
  selector:
    matchLabels:
      app: ipl
  template:
    metadata:
      labels:
        app: ipl
    spec:
      containers:
        - name: ipl
          image: muralisocial123/ipl:latest
          ports:
            - containerPort: 3000